### ISSUE TITLE
DOS newlines in agoric.sh

### ISSUE THREAD

**Issue by dckc** [pitalco/axelar-transfer#1]
At the `make install` step, I got:

```
---> Installing Agoric SDK
./network/agoric/agoric.sh: line 2: $'\r': command not found
```

looks like DOS CRLFs in

https://github.com/pitalco/axelar-transfer/blob/26ea5f84f3f50e679ab225e0a5ef9b9af69c55f3/network/agoric/agoric.sh#L2

I worked around it by doing `dos2unix ./network/agoric/agoric.sh`.

**Comment by schnetzlerjoe** [comment]
Good catch! Just fixed it and will push
