### ISSUE TITLE
cannot start axelar: cryptic cosmos-sdk diagnostics

### ISSUE THREAD

**Issue by dckc** [pitalco/axelar-transfer#2]
I'm stuck at the `make start` step. the `./network/data/axelar.log` shows:

```
{"level":"info","time":"2022-12-16T17:42:52-06:00","message":"file seeds.toml not found"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
...
```

**Comment by schnetzlerjoe** [comment]
Seems to be improper init of axelard. Did you run `make init`?

**Comment by schnetzlerjoe** [comment]
> I'm stuck at the `make start` step. the `./network/data/axelar.log` shows:
> 
> ```
> {"level":"info","time":"2022-12-16T17:42:52-06:00","message":"file seeds.toml not found"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]
> 
> goroutine 1 [running]:
> github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
> ...
> ```

Seems to be improper init of axelard. Did you run `make init`?

**Comment by schnetzlerjoe** [comment]
> I'm stuck at the `make start` step. the `./network/data/axelar.log` shows:
> 
> ```
> {"level":"info","time":"2022-12-16T17:42:52-06:00","message":"file seeds.toml not found"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]
> 
> goroutine 1 [running]:
> github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
> ...
> ```

Yeah try running again after `git pull`:

```bash
make install

make init

make start
```.

I am not having that issue but fixed up some bugs in make commands to maybe help

**Comment by dckc** [comment]
The first time, I made my clones in `$HOME/projects` but learned part way thru that they really do have to go in `$HOME`.

So today I started from scratch. same symptoms. hm.

version I used:
2022-12-22 96877c1 Bug init + install fixes

**Comment by schnetzlerjoe** [comment]
> The first time, I made my clones in `$HOME/projects` but learned part way thru that they really do have to go in `$HOME`.
> 
> So today I started from scratch. same symptoms. hm.
> 
> version I used:
> 2022-12-22 96877c1 Bug init + install fixes

Do me a favor. Run `ls $HOME/.axelar` and show the output for me please

**Comment by dckc** [comment]
```
$ ls $HOME/.axelar
config  data  keyring-file

$ ls $HOME/.axelar/config
app.toml  config.toml
```

**Comment by schnetzlerjoe** [comment]
What OS are you using? Is it linux?

**Comment by schnetzlerjoe** [comment]
> ```
> $ ls $HOME/.axelar
> config  data  keyring-file
> 
> $ ls $HOME/.axelar/config
> app.toml  config.toml
> ```


What OS are you using? Is it linux?

**Comment by dckc** [comment]
yes, linux

**Comment by schnetzlerjoe** [comment]
> yes, linux

What's the full stack trace for the goroutine if you don't mind?

**Comment by dckc** [comment]
the whole contents of `./network/data/axelar.log` is:

```
{"level":"info","time":"2022-12-29T15:06:26-06:00","message":"file seeds.toml not found"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/baseapp/test_helpers.go:44 +0x1d2
github.com/axelarnetwork/axelar-core/app.NewAxelarApp({0x2e8a0c0, 0xc000454d80}, {0x2e97658, 0xc000558168}, {0x0, 0x0}, 0x1, 0xc000253470, {0x7ffd6c6c4f12, 0x15}, ...)
        /home/runner/work/axelar-core/axelar-core/app/app.go:382 +0x31ee
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd.newApp({0x2e8a0c0, 0xc000454d80}, {0x2e97658, 0xc000558168}, {0x0, 0x0}, {0x2e6bd20?, 0xc001482ea0?})
        /home/runner/work/axelar-core/axelar-core/cmd/axelard/cmd/root.go:258 +0x894
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2e8dbc0, 0xc00128c180}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:252 +0x492
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012fa280?, {0xc0001c8870?, 0x0?, 0x9?})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0012fa280, {0xc0001c87e0, 0x9, 0x9})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011a7180)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1f81e16?, {0xc000569860, 0x16})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/runner/work/axelar-core/axelar-core/cmd/axelard/main.go:70 +0x4c5
```

**Comment by schnetzlerjoe** [comment]
> the whole contents of `./network/data/axelar.log` is:
> 
> ```
> {"level":"info","time":"2022-12-29T15:06:26-06:00","message":"file seeds.toml not found"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]
> 
> goroutine 1 [running]:
> github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
>         /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/baseapp/test_helpers.go:44 +0x1d2
> github.com/axelarnetwork/axelar-core/app.NewAxelarApp({0x2e8a0c0, 0xc000454d80}, {0x2e97658, 0xc000558168}, {0x0, 0x0}, 0x1, 0xc000253470, {0x7ffd6c6c4f12, 0x15}, ...)
>         /home/runner/work/axelar-core/axelar-core/app/app.go:382 +0x31ee
> github.com/axelarnetwork/axelar-core/cmd/axelard/cmd.newApp({0x2e8a0c0, 0xc000454d80}, {0x2e97658, 0xc000558168}, {0x0, 0x0}, {0x2e6bd20?, 0xc001482ea0?})
>         /home/runner/work/axelar-core/axelar-core/cmd/axelard/cmd/root.go:258 +0x894
> github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2e8dbc0, 0xc00128c180}, ...}, ...)
>         /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:252 +0x492
> github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012fa280?, {0xc0001c8870?, 0x0?, 0x9?})
>         /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:126 +0x169
> github.com/spf13/cobra.(*Command).execute(0xc0012fa280, {0xc0001c87e0, 0x9, 0x9})
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0011a7180)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
> github.com/spf13/cobra.(*Command).ExecuteContext(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
> github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1f81e16?, {0xc000569860, 0x16})
>         /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/cmd/execute.go:36 +0x1eb
> main.main()
>         /home/runner/work/axelar-core/axelar-core/cmd/axelard/main.go:70 +0x4c5
> ```
> 

Can you try manually downloading this version of Axelar here https://github.com/pitalco/axelar-core ensuring you are using go v1.19. Then retry

**Comment by dckc** [comment]
I'm pretty sure I was using go1.18.4.

More on trying that version of axelar-core soon, I hope...

**Comment by dckc** [comment]
with go 1.9 and stuff...

```
{"level":"info","time":"2023-01-04T11:12:50-06:00","message":"file seeds.toml not found"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e8d2]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).NewContext(_, _, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/baseapp/test_helpers.go:44 +0x1d2
github.com/axelarnetwork/axelar-core/app.NewAxelarApp({0x2e8a0c0, 0xc00120e660}, {0x2e97658, 0xc0000100c0}, {0x0, 0x0}, 0x1, 0xc001362600, {0x7ffdcae3df04, 0x15}, ...)
        /home/runner/work/axelar-core/axelar-core/app/app.go:382 +0x31ee
github.com/axelarnetwork/axelar-core/cmd/axelard/cmd.newApp({0x2e8a0c0, 0xc00120e660}, {0x2e97658, 0xc0000100c0}, {0x0, 0x0}, {0x2e6bd20?, 0xc000020b60?})
        /home/runner/work/axelar-core/axelar-core/cmd/axelard/cmd/root.go:258 +0x894
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x2e8dbc0, 0xc0012b3ce0}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:252 +0x492
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0000ebb80?, {0xc0012902d0?, 0x0?, 0x9?})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0000ebb80, {0xc001290240, 0x9, 0x9})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b0000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1f81e16?, {0xc000161878, 0x16})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.6/server/cmd/execute.go:36 +0x1eb
main.main()
        /home/runner/work/axelar-core/axelar-core/cmd/axelard/main.go:70 +0x4c5
```

**Comment by dckc** [comment]
diagnosis: a stray `~/bin/axelard` in my environment.

@schnetzlerjoe said the diagnostic could have been a lot better and talked about getting that fixed in cosmos-sdk.
